on:
  push:
    branches:
      - main
      - dev

jobs:
  vpn-test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls

      - name: setup vpn config
        run: echo "${{ secrets.OVPN_FILE }}" > config.ovpn

      - name: install openvpn
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Connect VPN
        run: sudo openvpn --config config.ovpn --daemon --log vpn.log

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until curl -s --connect-timeout 5 -o /dev/null http://verdaccio.us-west-2.elasticbeanstalk.com; do sleep 2; done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '13.11.0'

      - run: npm_config_registry=http://verdaccio.us-west-2.elasticbeanstalk.com/ npm i -g @boyle/bui

      - run: npm -g ls

      - name: kill vpn connection
        if: always()
        run: |
          sudo killall openvpn
          rm config.ovpn
